// Game forms re-exports
export { default as GameScoreFormDialog } from './score-form-dialog.vue'
export { GameDeleteFormDialog, GameBatchDeleteFormDialog } from './delete-form-dialog'
export { default as GameMetadataUpdateFormDialog } from './metadata-update-form-dialog/metadata-update-form-dialog.vue'
export { default as GameBatchMetadataUpdateFormDialog } from './metadata-update-form-dialog/batch-metadata-update-form-dialog.vue'
export { GameExternalIdsFormDialog } from './external-ids-form-dialog'
export { default as GameInfoFormDialog } from './info-form-dialog.vue'
export { default as GameNameFormDialog } from './name-form-dialog.vue'
export { default as GameOriginalNameFormDialog } from './original-name-form-dialog.vue'
export { default as GameDescriptionFormDialog } from './description-form-dialog.vue'
export { default as GameStatusFormDialog } from './status-form-dialog.vue'
export { default as GameLastActiveFormDialog } from './last-active-form-dialog.vue'
export { GameTagsFormDialog } from './tags-form-dialog'
export { GameDurationFormDialog } from './duration-form-dialog'
export { GameRelatedSitesFormDialog } from './related-sites-form-dialog'
export { GameLaunchConfigFormDialog } from './launch-config-form-dialog'
export { GameCharactersFormDialog } from './characters-form-dialog'
export { GameCompaniesFormDialog } from './companies-form-dialog'
export { GamePersonsFormDialog } from './persons-form-dialog'
export { GameMediaFormDialog } from './media-form-dialog'
export { default as GameNotesFormDialog } from './notes-form-dialog.vue'
export { default as GameSavesFormDialog } from './saves-form-dialog.vue'
